In [33]:
import pandas as pd
import numpy as np
# Import our dependencies
import pandas as pd
import matplotlib as plt
from sklearn.datasets import make_blobs
import sklearn as skl
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler
from imblearn.combine import SMOTEENN
from tensorflow.keras.layers import Dense, Dropout
# Use sklearn to split dataset
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

In [3]:
stolen_df = pd.read_csv('stolen_df_2.csv')
stolen_df.head()

Result Exchange Arm_Strength  Sprint        Date  runner_id  \
0       1     0.74         84.9    28.0  2021-04-01     545341   
1       0     0.75         81.4    27.3  2021-04-01     643565   
2       0     0.75         81.4    27.3  2021-04-01     643565   
3       0     0.73         79.0    27.9  2020-09-30     666185   
4       1      0.7         83.2    27.8  2020-09-30     502054   

      runner_name  Result_1  Exchange_1  Arm_Strength_1  ...  Arm_Strength_3  \
0  Randal Grichuk         1        0.74            84.9  ...            84.9   
1   Mike Tauchman         0        0.75            81.4  ...            81.4   
2   Mike Tauchman         0        0.75            81.4  ...            81.4   
3   Dylan Carlson         0        0.73            79.0  ...            79.0   
4      Tommy Pham         1        0.70            83.2  ...            83.2   

   Sprint_3  Result_4  Exchange_4  Arm_Strength_4  Sprint_4  Result_5  \
0      27.0         0        0.74            84.9      27.7         0   
1       NaN         1        0.75            81.4      30.5         1   
2       NaN         1        0.75            81.4      30.5         1   
3      27.6         1        0.73            79.0      27.6         0   
4       NaN         1        0.70            83.2       NaN         1   

   Exchange_5  Arm_Strength_5  Sprint_5  
0        0.74            84.9      25.0  
1        0.75            81.4       NaN  
2        0.75            81.4       NaN  
3        0.73            79.0      28.6  
4        0.70            83.2      27.4  

[5 rows x 27 columns]

In [4]:
stolen_df.columns

Index(['Result', 'Exchange', 'Arm_Strength', 'Sprint', 'Date', 'runner_id',
       'runner_name', 'Result_1', 'Exchange_1', 'Arm_Strength_1', 'Sprint_1',
       'Result_2', 'Exchange_2', 'Arm_Strength_2', 'Sprint_2', 'Result_3',
       'Exchange_3', 'Arm_Strength_3', 'Sprint_3', 'Result_4', 'Exchange_4',
       'Arm_Strength_4', 'Sprint_4', 'Result_5', 'Exchange_5',
       'Arm_Strength_5', 'Sprint_5'],
      dtype='object')

In [5]:
stolen_df.dropna(inplace=True)

In [6]:
len(stolen_df)

12768

In [11]:
stolen_df.replace(' --', 0, inplace=True)

In [18]:
stolen_df.sort_values(by='Date')

Result Exchange Arm_Strength  Sprint        Date  runner_id  \
37569       1     0.75         80.1    28.0  2016-04-09     543807   
37568       1     0.75         80.1    28.4  2016-04-09     514888   
26534       1     0.75         80.1    28.0  2016-04-09     543807   
26533       1     0.75         80.1    28.4  2016-04-09     514888   
32327       1     0.75         80.1    28.4  2016-04-09     514888   
...       ...      ...          ...     ...         ...        ...   
26565       1     0.78         84.6    29.6  2023-09-29     682998   
26564       1     0.62         83.5    27.1  2023-09-29     514888   
26562       1     0.78         84.6    27.5  2023-09-29     607054   
26540       1     0.62         83.5    26.0  2023-09-30     663656   
9648        1     0.62         83.5    26.0  2023-09-30     663656   

           runner_name  Result_1  Exchange_1  Arm_Strength_1  ...  \
37569  George Springer         1        0.75            80.1  ...   
37568      Jose Altuve         1        0.75            80.1  ...   
26534  George Springer         1        0.75            80.1  ...   
26533      Jose Altuve         1        0.75            80.1  ...   
32327      Jose Altuve         1        0.75            80.1  ...   
...                ...       ...         ...             ...  ...   
26565   Corbin Carroll         1        0.69            85.4  ...   
26564      Jose Altuve         1        0.62            83.5  ...   
26562    Jace Peterson         1        0.69            85.4  ...   
26540      Kyle Tucker         1        0.62            83.5  ...   
9648       Kyle Tucker         1        0.62            83.5  ...   

       Arm_Strength_3  Sprint_3  Result_4  Exchange_4  Arm_Strength_4  \
37569            80.1      26.3         1        0.75            80.1   
37568            80.1      26.3         1        0.75            80.1   
26534            80.1      26.3         1        0.75            80.1   
26533            80.1      26.3         1        0.75            80.1   
32327            80.1      26.3         1        0.75            80.1   
...               ...       ...       ...         ...             ...   
26565            85.4      30.5         1        0.69            85.4   
26564            83.5      28.6         1        0.62            83.5   
26562            85.4      30.5         1        0.69            85.4   
26540            83.5      29.3         1        0.62            83.5   
9648             83.5      29.3         1        0.62            83.5   

       Sprint_4  Result_5  Exchange_5  Arm_Strength_5  Sprint_5  
37569      27.9         0        0.75            80.1      26.3  
37568      27.9         0        0.75            80.1      26.3  
26534      27.9         0        0.75            80.1      26.3  
26533      27.9         0        0.75            80.1      26.3  
32327      27.9         0        0.75            80.1      26.3  
...         ...       ...         ...             ...       ...  
26565      30.5         1        0.69            85.4      27.1  
26564      28.5         0        0.62            83.5      27.7  
26562      30.5         1        0.69            85.4      27.1  
26540      28.5         0        0.62            83.5      27.7  
9648       28.5         0        0.62            83.5      27.7  

[12768 rows x 27 columns]

In [27]:
test_df = stolen_df.loc[stolen_df['Date'] < '2022-09-30']
validate_df = stolen_df.loc[stolen_df['Date'] > '2022-09-30']

In [35]:
chosen = 'Result'

X = test_df.drop(columns=[chosen, 'Date', 'runner_id', 'runner_name'])

# Define the target set.
y = test_df[chosen].ravel()
y[:5]

array([1, 0, 1, 1, 1])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78) 


# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

# Making predictions using the testing data.
predictions = rf_model.predict(X_test)

In [22]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)
cm

array([[ 614,   22],
       [   6, 2038]])

In [23]:
# Displaying results previous 2023
print("Classification Report")
print(classification_report(y_test, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       636
           1       0.99      1.00      0.99      2044

    accuracy                           0.99      2680
   macro avg       0.99      0.98      0.99      2680
weighted avg       0.99      0.99      0.99      2680



In [16]:
# Displaying results
print("Classification Report")
print(classification_report(y_test, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.89      0.65      0.75       982
           1       0.92      0.98      0.95      4052

    accuracy                           0.92      5034
   macro avg       0.90      0.81      0.85      5034
weighted avg       0.91      0.92      0.91      5034



In [24]:
X_test

Exchange Arm_Strength  Sprint  Result_1  Exchange_1  Arm_Strength_1  \
26384     0.84         85.2    28.0         1        0.84            85.2   
34450     0.75         86.3    28.5         1        0.75            86.3   
32024     0.84         85.2    30.0         0        0.84            85.2   
34007     0.71         79.5    28.6         1        0.71            79.5   
33346     0.72         79.8    27.8         1        0.72            79.8   
...        ...          ...     ...       ...         ...             ...   
36227     0.66         82.6    27.0         1        0.66            82.6   
6710      0.72         76.7    27.2         1        0.72            76.7   
35635     0.73         86.1    27.1         1        0.73            86.1   
20813     0.75         81.1    28.2         1        0.75            81.1   
36997     0.76         76.9    25.7         1        0.76            76.9   

       Sprint_1  Result_2  Exchange_2  Arm_Strength_2  ...  Arm_Strength_3  \
26384      27.3         1        0.84            85.2  ...            85.2   
34450      27.9         1        0.75            86.3  ...            86.3   
32024      27.9         1        0.84            85.2  ...            85.2   
34007      28.0         1        0.71            79.5  ...            79.5   
33346      24.8         1        0.72            79.8  ...            79.8   
...         ...       ...         ...             ...  ...             ...   
36227      24.2         0        0.66            82.6  ...            82.6   
6710       26.1         0        0.72            76.7  ...            76.7   
35635      28.0         0        0.73            86.1  ...            86.1   
20813      28.4         1        0.75            81.1  ...            81.1   
36997      28.2         1        0.76            76.9  ...            76.9   

       Sprint_3  Result_4  Exchange_4  Arm_Strength_4  Sprint_4  Result_5  \
26384      28.7         1        0.84            85.2      27.4         1   
34450      28.7         1        0.75            86.3      23.8         1   
32024      27.1         1        0.84            85.2      28.9         1   
34007      27.1         1        0.71            79.5      28.5         1   
33346      27.2         1        0.72            79.8      27.9         1   
...         ...       ...         ...             ...       ...       ...   
36227      27.1         1        0.66            82.6      25.5         1   
6710       29.4         1        0.72            76.7      27.5         1   
35635      25.8         1        0.73            86.1      27.7         1   
20813      28.2         1        0.75            81.1      28.0         1   
36997      28.2         1        0.76            76.9      28.0         1   

       Exchange_5  Arm_Strength_5  Sprint_5  
26384        0.84            85.2      27.1  
34450        0.75            86.3      28.7  
32024        0.84            85.2      27.0  
34007        0.71            79.5      27.7  
33346        0.72            79.8      25.7  
...           ...             ...       ...  
36227        0.66            82.6      26.8  
6710         0.72            76.7      27.5  
35635        0.73            86.1      28.4  
20813        0.75            81.1      27.4  
36997        0.76            76.9      28.0  

[2680 rows x 23 columns]

In [28]:
chosen = 'Result'

X = validate_df.drop(columns=[chosen, 'Date', 'runner_id', 'runner_name'])

# Define the target set.
y = validate_df[chosen].ravel()
y[:5]

array([1, 1, 1, 1, 1])

In [29]:
# Making predictions using the testing data.
predictions = rf_model.predict(X)

In [30]:
# Displaying results
print("Classification Report")
print(classification_report(y, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.63      0.40      0.49       370
           1       0.88      0.95      0.91      1681

    accuracy                           0.85      2051
   macro avg       0.76      0.67      0.70      2051
weighted avg       0.83      0.85      0.84      2051



In [31]:
from itertools import combinations, product
lr = [0.01, 0.02, 0.005, 0.05]

mf = ["sqrt", "log2", 0.5, 0.8]

md = [5, 10, 15, 20, 30, 50, 80]

n_e = [150, 200, 300, 400, 500, 1000]

min_sp = [2, 3, 5, 10]



combos = list(product(lr, mf, md, n_e ,min_sp))

len(combos)

2688

In [36]:
results = {}

# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

from sklearn.ensemble import GradientBoostingClassifier

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

for combo in combos:


    classifier = GradientBoostingClassifier(n_estimators=combo[3],
    learning_rate=combo[0],
    max_features=combo[1],
    max_depth=combo[2],
    min_samples_split=combo[4],
    random_state=0)
    classifier.fit(X_train_scaled, y_train.ravel())
    
    # Make predictions on test data
    y_pred = classifier.predict(X_test_scaled)
    
    precision = precision_score(y_test, classifier.predict(X_test_scaled))
    
    recall = recall_score(y_test, y_pred)

    
    results[combo] = {'Training': f"{classifier.score(X_train_scaled, y_train)}",'Precision':precision, 'Recall': recall}

In [41]:
results_df = pd.DataFrame.from_dict(results, orient='index').sort_values(by='Precision', ascending=False)
results_df.head(10)

Training  Precision    Recall
0.05 0.5  5  1000 5                  1.0   0.994152  0.998043
     0.8  5  1000 5                  1.0   0.994152  0.998043
                  3                  1.0   0.994146  0.997065
                  2                  1.0   0.993181  0.997554
     log2 20 200  2                  1.0   0.992694  0.997065
     0.5  5  1000 10  0.9998755754634814   0.992694  0.997065
     sqrt 20 200  2                  1.0   0.992694  0.997065
     0.5  5  1000 3                  1.0   0.992218  0.998043
     sqrt 10 300  10                 1.0   0.992218  0.998043
     log2 10 300  10                 1.0   0.992218  0.998043

In [42]:
results_df['Max Depth'] = results_df.apply(lambda row: row.name[2], axis =1)
results_df['Min Feat'] = results_df.apply(lambda row: row.name[1], axis =1)
results_df['N'] = results_df.apply(lambda row: row.name[-1], axis =1)

In [43]:
results_df.loc[(results_df['Recall'] >= 0.2) & (results_df['Max Depth'] <= 50)].head(10)


Training  Precision    Recall  Max Depth  \
0.05 0.5  5  1000 5                  1.0   0.994152  0.998043          5   
     0.8  5  1000 5                  1.0   0.994152  0.998043          5   
                  3                  1.0   0.994146  0.997065          5   
                  2                  1.0   0.993181  0.997554          5   
     log2 20 200  2                  1.0   0.992694  0.997065         20   
     0.5  5  1000 10  0.9998755754634814   0.992694  0.997065          5   
     sqrt 20 200  2                  1.0   0.992694  0.997065         20   
     0.5  5  1000 3                  1.0   0.992218  0.998043          5   
     sqrt 10 300  10                 1.0   0.992218  0.998043         10   
     log2 10 300  10                 1.0   0.992218  0.998043         10   

                     Min Feat   N  
0.05 0.5  5  1000 5       0.5   5  
     0.8  5  1000 5       0.8   5  
                  3       0.8   3  
                  2       0.8   2  
     log2 20 200  2      log2   2  
     0.5  5  1000 10      0.5  10  
     sqrt 20 200  2      sqrt   2  
     0.5  5  1000 3       0.5   3  
     sqrt 10 300  10     sqrt  10  
     log2 10 300  10     log2  10

In [44]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

from sklearn.ensemble import GradientBoostingClassifier

classifier = GradientBoostingClassifier(n_estimators=1000,
learning_rate=0.05,
max_features=0.5,
max_depth=5,
min_samples_split=5,
random_state=0)
classifier.fit(X_train_scaled, y_train.ravel())

precision = precision_score(y_test, classifier.predict(X_test_scaled))

print("Learning rate: ", 1)
print("Accuracy score (training): {0:.3f}".format(
   classifier.score(
       X_train_scaled,
       y_train)))
print(f"Accuracy score (validation): {precision}")

Learning rate:  1
Accuracy score (training): 1.000
Accuracy score (validation): 0.9941520467836257


In [45]:
chosen = 'Result'

X = validate_df.drop(columns=[chosen, 'Date', 'runner_id', 'runner_name'])

# Define the target set.
y = validate_df[chosen].ravel()
y[:5]

array([1, 1, 1, 1, 1])

In [46]:
X_scaled = X_scaler.transform(X)

predictions = classifier.predict(X_scaled)

results = np.round(predictions).astype(int).tolist()

In [47]:

print(classification_report(y, results))

              precision    recall  f1-score   support

           0       0.66      0.72      0.69       370
           1       0.94      0.92      0.93      1681

    accuracy                           0.88      2051
   macro avg       0.80      0.82      0.81      2051
weighted avg       0.89      0.88      0.88      2051



In [48]:
import joblib
joblib.dump(X_scaler, 'gradient_scale.pkl')
joblib.dump(classifier, 'gradient.pkl')

['gradient.pkl']